#!/bin/bash

export ZMICRO_DATA_PARENT="${ZMICRO_DATA_PARENT}"
if [ "$(uname -s)" = "Darwin" ]; then
  export ZMICRO_DATA_PARENT=/opt
fi

export PLUGIN_NVM_DATA=${ZMICRO_DATA_PARENT}/data/plugins/nvm
export PLUGIN_NVM_VERSIONS=${PLUGIN_NVM_DATA}/versions
export PLUGIN_NVM_VERSION_CURRENT=${PLUGIN_NVM_DATA}/current

export PLUGIN_NVM_SOURCE_VERSION=""
if [ -f "$PWD/.nvmrc" ]; then
  PLUGIN_NVM_SOURCE_VERSION="$(cat $PWD/.nvmrc)"
else
  if [ -f "$PLUGIN_NVM_VERSION_CURRENT" ]; then
    PLUGIN_NVM_SOURCE_VERSION="$(cat $PLUGIN_NVM_VERSION_CURRENT)"
  fi
fi

# nvm
if [ -z "$PLUGIN_NVM_SOURCE_VERSION" ]; then
  export PLUGIN_NVM_NODE_DEFAULT_VERSION=v16.17.0
  export PLUGIN_NVM_SOURCE_VERSION=$PLUGIN_NVM_NODE_DEFAULT_VERSION
fi
if [ ! -d "$PLUGIN_NVM_VERSIONS/$PLUGIN_NVM_SOURCE_VERSION" ]; then
  if [ -d "$PLUGIN_NVM_VERSIONS" ]; then
    if [ -n "$(ls $PLUGIN_NVM_VERSIONS)" ]; then
      PLUGIN_NVM_SOURCE_VERSION=$(ls $PLUGIN_NVM_VERSIONS | grep $PLUGIN_NVM_SOURCE_VERSION | sort -rV | head -n 1)
    fi
  fi
fi
export PLUGIN_NVM_NODE_CURRENT_VERSION=$PLUGIN_NVM_SOURCE_VERSION

# node
export NODE_HOME=$PLUGIN_NVM_VERSIONS/$PLUGIN_NVM_SOURCE_VERSION
export NODE_USER_HOME=$HOME/.node
export PATH=$NODE_USER_HOME/bin:$NODE_HOME/bin:$PATH

# usage: as nvm.sh
# [ -s "$ZMICRO_HOME/plugins/nvm/source" ] && \. $ZMICRO_HOME/plugins/nvm/source
