#!/bin/bash

export ZMICRO_DATA_PARENT="${ZMICRO_DATA_PARENT}"
if [ "$(uname -s)" = "Darwin" ]; then
  export ZMICRO_DATA_PARENT=/opt
fi

export PLUGIN_XVM_DATA=${ZMICRO_DATA_PARENT}/data/plugins/nvm
export PLUGIN_XVM_VERSIONS=${PLUGIN_XVM_DATA}/versions
export PLUGIN_XVM_VERSION_CURRENT=${PLUGIN_XVM_DATA}/current

version=""
if [ -f "$PWD/.nvmrc" ]; then
  version="$(cat $PWD/.nvmrc)"
else
  if [ -f "$PLUGIN_XVM_VERSION_CURRENT" ]; then
    version="$(cat $PLUGIN_XVM_VERSION_CURRENT)"
  fi
fi

# nvm
if [ -z "$version" ]; then
  export PLUGIN_NVM_NODE_DEFAULT_VERSION=v16.17.0
  export version=PLUGIN_NVM_NODE_DEFAULT_VERSION
fi
if [ ! -d "$PLUGIN_XVM_VERSIONS/$version" ]; then
  if [ -d "$PLUGIN_XVM_VERSIONS" ]; then
    if [ -n "$(ls $PLUGIN_XVM_VERSIONS)" ]; then
      version=$(ls $PLUGIN_XVM_VERSIONS | grep $version | sort -rV | head -n 1)
    fi
  fi
fi
export PLUGIN_NVM_NODE_CURRENT_VERSION=$version

# node
export NODE_HOME=$PLUGIN_XVM_VERSIONS/$version
export NODE_USER_HOME=$HOME/.node
export PATH=$NODE_USER_HOME/bin:$NODE_HOME/bin:$PATH

# usage: as nvm.sh
# [ -s "$ZMICRO_HOME/plugins/nvm/source" ] && \. $ZMICRO_HOME/plugins/nvm/source
