#!/bin/bash

help() {
  echo "Usage:"
  echo "  nvm use"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # echo $PLUGIN_NVM_NODE_BIN

  [ -s "$ZMICRO_HOME/plugins/nvm/source" ] && \. $ZMICRO_HOME/plugins/nvm/source
  echo "$NODE_HOME/bin"
}

run() {
  core $@
}

run $@
