#!/bin/bash

help() {
  echo "Usage:"
  echo "  nvm exec"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local version=$1
  version=$(vm::version_ensure_prefix_v $version)

  nvm::exec $version ${@:1}
}

run() {
  core $@
}

run $@
