#!/bin/bash

name() {
  local version=$(plugin::get_version $PLUGIN_NVM_NAME)
  echo "Node Version Manager ($(color::success $version))"
}

description() {
  echo "Node Version Manager is a tool for managing multiple Node.js versions."
}

usage() {
  echo "Usage:"
  echo "  znvm install <version>   - Install Node version"
  echo "  znvm use <version>       - Use Node version"
  echo "  znvm remove <version>    - Remove Node version"
  echo "  znvm ls                  - List the Node.js versions installed"
  echo "  znvm ls-remote           - List all Node.js versions from remote"
  echo "  znvm current             - Show current Node version"
  echo "  znvm exec                - Enter new shell with node -v for tmp"
  echo "  znvm pack [dist_dir]     - Pack Current Node Version to a tar.gz file"
  echo "  znvm help                - Show help"
}

example() {
  echo "Example:"
  echo "  znvm install $PLUGIN_NVM_NODE_DEFAULT_VERSION"
  echo "  znvm use $PLUGIN_NVM_NODE_DEFAULT_VERSION"
  echo "  znvm remove $PLUGIN_NVM_NODE_DEFAULT_VERSION"
  echo "  znvm ls"
  echo "  znvm ls-remote"
  echo "  znvm current"
  echo "  znvm workon v16 node -v"
  echo "  znvm workon v12 node -v"
  echo "  znvm workon v16 npm run build"
}

core() {
  name
  echo ""
  description
  echo ""
  usage
  echo ""
  example
}

run() {
  core $@
}

run $@
