#!/bin/bash

name() {
  local version=$(plugin::get_version $PLUGIN_NVM_NAME)
  echo "Node Version Manager ($(color::success $version))"
}

description() {
  echo "Node Version Manager is a tool for managing multiple Node.js versions."
}

usage() {
  echo "Usage:"
  echo "  nvm install <version>   - Install Node version"
  echo "  nvm use <version>       - Use Node version"
  echo "  nvm remove <version>    - Remove Node version"
  echo "  nvm ls                  - List the Node.js versions installed"
  echo "  nvm ls-remote           - List all Node.js versions from remote"
  echo "  nvm current             - Show current Node version"
  echo "  nvm exec                - Enter new shell with node -v for tmp"
  echo "  nvm pack [dist_dir]     - Pack Current Node Version to a tar.gz file"
  echo "  nvm help                - Show help"
}

example() {
  echo "Example:"
  echo "  nvm install $PLUGIN_NVM_NODE_DEFAULT_VERSION"
  echo "  nvm use $PLUGIN_NVM_NODE_DEFAULT_VERSION"
  echo "  nvm remove $PLUGIN_NVM_NODE_DEFAULT_VERSION"
  echo "  nvm ls"
  echo "  nvm ls-remote"
  echo "  nvm current"
  echo "  nvm workon v16 node -v"
  echo "  nvm workon v12 node -v"
  echo "  nvm workon v16 npm run build"
}

core() {
  name
  echo ""
  description
  echo ""
  usage
  echo ""
  example
}

run() {
  core $@
}

run $@
