#!/bin/bash

help() {
  echo "Usage:"
  echo "  nvm install [version]"
  echo ""
  echo "Options:"
  echo "  version    - Install Node version, default: $PLUGIN_NVM_NODE_DEFAULT_VERSION"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local version=$1
  if [ -z "$version" ]; then
    version=$PLUGIN_NVM_NODE_DEFAULT_VERSION
  fi

  nvm::install $version

  if [ -f "$HOME/.zshrc" ]; then
    log::success "load nodejs by reloading env with $(color::success "source $HOME/.zshrc")"
  elif [ -f "$HOME/.bashrc" ]; then
    log::success "load nodejs by reloading env with $(color::success "source $HOME/.bashrc")"
  else
    log::success "restart your shell to load nodejs"
  fi
}

run() {
  core $@
}

run $@
