#!/bin/bash

load inquirer

help() {
  echo "Usage:"
  echo "  znvm use"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local version=$1
  
  if [ -z "$version" ]; then
    local availables=($(nvm::list))
    inquirer::select "Select ?" availables version
  fi

  nvm::use $version

  echo "current: $version"
}

run() {
  core $@
}

run $@
