#!/bin/bash

load inquirer

help() {
  echo "Usage:"
  echo "  nvm use"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local version=$1

  if [ -z "$version" ]; then
    local availables=($(nvm::list))
    inquirer::select "Select ?" availables version
  fi

  if [ "$(nvm::has_version_local $version)" = "true" ]; then
    local local_version=$(nvm::get_version_local $version)
    nvm::use $local_version
    echo "current: $version ($local_version)"
    exit 0
  fi

  nvm::use $version

  echo "current: $(nvm::current)"
}

run() {
  core $@
}

run $@
