#!/bin/bash

load inquirer

help() {
  echo "Make it easy to work on specific node version"
  echo ""
  echo "Usage:"
  echo "  znvm workon <version> [command] [args ...]"
  echo ""
  echo "Example:"
  echo "  znvm workon v16 node -v"
  echo "  znvm workon v12 node -v"
  echo "  znvm workon v16 npm run build"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local version=$1
  local command=${@:2}
  
  if [ -z "$version" ]; then
    local availables=($(nvm::list))
    inquirer::select "Select ?" availables version
  fi

  if [ -z "$command" ]; then
    command="node"
  fi

  if [ -z "$version" ]; then
    log::error "version is required"
  fi

  nvm::workon "$version" "$command"
}

run() {
  core $@
}

run $@
