#!/bin/bash

# nvm::current gets the current version of Node.js
nvm::current() {
  [ -s "$ZMICRO_HOME/plugins/nvm/source" ] && \. $ZMICRO_HOME/plugins/nvm/source

  echo $PLUGIN_NVM_NODE_CURRENT_VERSION
}

export -f nvm::current
