#!/bin/bash

# nvm::current gets the current version of Node.js
nvm::current() {
  if [ "$(os::has_command node)" = "true" ]; then
    node -v
    return
  fi

  echo "node not found"
}

export -f nvm::current
