#!/bin/bash

nvm::download() {
  local version=$1
  local dist_dir=$2
  if [ -z "$version" ] || [ -z "$dist_dir" ]; then
    log::error "[nvm::download] version and dist_dir are required"
    exit 1
  fi

  local os_name=$(os::platform)
  local os_arch=$(os::arch)
  local filename=node-${version}-${os_name}-${os_name}
  local filename_tgz=${filename}.tar.gz

  local tar_gz_url=$(nvm::internal_install_get_download_url $version)

  # 302 redirect
  curl -I $tar_gz_url 2>/dev/null | head -n 1 | grep "302" >> /dev/null 2>&1
  if [ "$?" = "0" ]; then
    local location=$(curl -I $tar_gz_url 2>/dev/null | grep location | awk '{print $2}')

    # fix location
    # stackoverflow: https://stackoverflow.com/questions/70660633/curl-3-url-using-bad-illegal-format-or-missing-url-in-bash-windows
    location=$(echo $location | sed 's/\r//g')

    # 404
    curl -I $location 2>/dev/null | head -n 1 | grep "404" >> /dev/null 2>&1
    if [ "$?" = "0" ]; then
      log::error "[nvm::download] invalid version: $version"
      log::error "[nvm::download] see more version at $PLUGIN_NVM_NODE_SOURCE_OFFICIAL"
      exit 1
    fi
  else
    # 404
    curl -I $tar_gz_url 2>/dev/null | head -n 1 | grep "404" >> /dev/null 2>&1
    if [ "$?" = "0" ]; then
      log::error "[nvm::download] invalid version: $version"
      log::error "[nvm::download] see more version at $PLUGIN_NVM_NODE_SOURCE_OFFICIAL"
      exit 1
    fi
  fi

  # download
  wget -c $tar_gz_url -O $dist_dir/$filename_tgz
}

export -f nvm::download

