#!/bin/bash

# nvm::exec enters a new shell with Node.js
nvm::exec() {
  local version=$1
  if [ -n "$version" ]; then
    version=$(vm::version_ensure_prefix_v $version)
    PLUGIN_NVM_NODE_HOME=$PLUGIN_NVM_VERSIONS/$version
  fi

  which node >>/dev/null 2>&1
  if [ $? -eq 0 ]; then
    log::error "[nvm::exec] found node, you should use 'nvm use' instead of 'nvm exec'"
    exit 1
  fi

  export NODE_HOME=${PLUGIN_NVM_NODE_HOME}
  export NODE_USER_HOME=${PLUGIN_NVM_NODE_PATH}
  export PATH=$NODE_USER_HOME/bin:$NODE_HOME/bin:$PATH

  exec $SHELL
}

export -f nvm::exec
