#!/bin/bash

# nvm::remove remove the node version
# if the version is current, it will be unset
nvm::remove() {
  local version=$1
  if [ -z "$version" ]; then
    log::error "[nvm::use] version is required"
    exit 1
  fi

  if [ ! -d "$PLUGIN_NVM_VERSIONS/$version" ]; then
    log::error "[nvm::use] version $version not found"
    exit 1
  fi

  sudo rm -rf $PLUGIN_NVM_VERSIONS/$version

  if [ "$(nvm::current)" == "$version" ]; then
    local new_version=$(nvm::list | head -n 1)
    if [ -n "$new_version" ]; then
      nvm::use $new_version
    else
      echo "" > $PLUGIN_NVM_VERSION_CURRENT
    fi
  fi
}

export -f nvm::remove
