#!/bin/bash

# nvm::use change the current version of go
nvm::use() {
  local version=$1
  if [ -z "$version" ]; then
    log::error "[nvm::use] version is required"
    exit 1
  fi

  # smart detect
  version=$(vm::version_ensure_prefix_v $version)

  if [ ! -d "$PLUGIN_NVM_VERSIONS/$version" ]; then
    # log::error "[nvm::use] version $version not found"
    # exit 1
    nvm::install $version
    nvm::use $version
    return
  fi

  # @TODO force sudo
  sudo ls >> /dev/null 2>&1

  if [ -d $PLUGIN_NVM_NODE_HOME ]; then
    # if not a link
    file $PLUGIN_NVM_NODE_HOME | grep symbolic >> /dev/null 2>&1
    if [ "$?" != "0" ]; then
      sudo rm -rf $PLUGIN_NVM_NODE_HOME
    else
      sudo rm -f $PLUGIN_NVM_NODE_HOME
    fi
  fi
  
  sudo ln -sf $PLUGIN_NVM_VERSIONS/$version $PLUGIN_NVM_NODE_HOME
  echo $version > $PLUGIN_NVM_VERSION_CURRENT

  # apply env
  nvm::env
}

export -f nvm::use
