#!/bin/bash

# nvm::use change the current version of Node.js
nvm::use() {
  local version=$1
  if [ -z "$version" ]; then
    log::error "[nvm::use] version is required"
    exit 1
  fi

  if [ "$version" = "default" ]; then
    version=$PLUGIN_NVM_NODE_DEFAULT_VERSION
  elif [ "$version" = "lts" ]; then
    version=$PLUGIN_NVM_NODE_LTS_VERSION
  elif [ "$version" = "latest" ]; then
    version=$PLUGIN_NVM_NODE_DEFAULT_VERSION
  fi

  # smart detect
  version=$(vm::version_ensure_prefix_v $version)

  if [ ! -d "$PLUGIN_NVM_VERSIONS/$version" ]; then
    # log::error "[nvm::use] version $version not found"
    # exit 1
    nvm::install $version
    nvm::use $version
    return
  fi

  # @TODO force sudo
  sudo ls >>/dev/null 2>&1

  if [ -d $PLUGIN_NVM_NODE_HOME ]; then
    # if not a link
    if [ "$(os::has_command file)" = "true" ]; then
      file $PLUGIN_NVM_NODE_HOME | grep symbolic >>/dev/null 2>&1
      if [ "$?" != "0" ]; then
        sudo rm -rf $PLUGIN_NVM_NODE_HOME
      else
        sudo rm -f $PLUGIN_NVM_NODE_HOME
      fi
    fi
  fi

  if [ ! -d "$PLUGIN_NVM_USR_LOCAL_BIN" ]; then
    sudo mkdir -p $PLUGIN_NVM_USR_LOCAL_BIN
  fi

  sudo ln -sf $PLUGIN_NVM_VERSIONS/$version $PLUGIN_NVM_NODE_HOME
  # @FIX n
  if [ -d "$PLUGIN_NVM_USR_LOCAL_BIN/node" ]; then
    sudo rm -rf $PLUGIN_NVM_USR_LOCAL_BIN/node
  elif [ -f "$PLUGIN_NVM_USR_LOCAL_BIN/node" ]; then
    sudo rm -f $PLUGIN_NVM_USR_LOCAL_BIN/node
  fi

  sudo ln -sf $PLUGIN_NVM_NODE_BIN/node $PLUGIN_NVM_USR_LOCAL_BIN/node
  #
  echo $version >$PLUGIN_NVM_VERSION_CURRENT

  # apply env
  nvm::env
}

export -f nvm::use
